[package]
name = "rmodbus"
version = "0.3.6"
authors = ["Sergei S. <div@altertech.com>"]
edition = "2018"
license = "Apache-2.0"
repository = "https://github.com/alttch/rmodbus"
description = "Fast and platform-independent Modbus server framework"
readme = "README.md"
keywords = ["modbus", "server", "hardware", "nostd"]

[lib]
name ="rmodbus"
path = "src/lib.rs"

[dependencies]
ieee754 = "0.2.6"
fixedvec = { version = "0.2.4", optional = true }
spin = { version = "0.5.2", optional = true }
lazy_static_std = { package="lazy_static", version = "1.4.0", optional=true }
lazy_static_nostd = { package="lazy_static", version = "1.4.0", optional=true, features=["spin_no_std"] }

[package.metadata.docs.rs]
features = ["std"]

[package.metadata.playground]
features = ["std"]

[features]
std = ["lazy_static_std"]
nostd = ["fixedvec", "spin", "lazy_static_nostd"]
single = []
smallcontext = []

[dev-dependencies]
rand = "0.7.3"
crc16 = "0.4.0"

#!test-threads = 1
